version: '3'

services:
  # Serviço do MySQL
  db:
    image: mysql:8.0.39
    container_name: database-crm
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - database-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - crm-network

  # Serviço do Backend (Laravel)
  back:
    build:
      context: ./back/.docker/local
      dockerfile: Dockerfile
    container_name: back-crm
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./back:/var/www  # Adicionando um volume para garantir que o código do back-end seja persistido
    networks:
      - crm-network   

  # Serviço do Frontend (React)
  front:
    build:
      context: ./front
      dockerfile: ./.docker/local/Dockerfile
    container_name: front-crm
    ports:
      - "3000:3000" 
    depends_on:
      - back
    volumes:
      - ./front:/app  # Adicionando um volume para garantir que o código do front-end seja persistido  
    networks:
      - crm-network  

volumes:
  database-data:


networks:
  crm-network:
    name: crm-network
