version: '3'

services:
  # Serviço do MySQL
  db:
    image: mysql:8.0
    container_name: database-crm
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - database-data:/var/lib/mysql

  # Serviço do Backend (Laravel)
  back:
    image: ryanmathias07/back
    container_name: back-crm
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy

  # Serviço do Frontend (React)
  front:
    image: ryanmathias07/front # Substitua pelo nome do seu repositório Docker Hub
    container_name: front-crm
    ports:
      - "3000:80" # Mapeando a porta 80 do container para a porta 3000 do host
    depends_on:
      - back

volumes:
  database-data:
