services:
  # Serviço do MySQL
  db:
    image: mysql:8.0
    container_name: database-crm
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55 
    volumes:
      - database-data:/var/lib/mysql
  
  # Serviço do Backend (Laravel)
  back:
    image: ryanmathias07/back
    container_name: back-crm
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  # # Serviço do Frontend (React)
  # front:
  #   build:
  #     context: ./front
  #   container_name: front-crm
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./front:/app
  #   depends_on:
  #     - back

volumes:
  database-data: