version: '3.8'

services:
  # Serviço do MySQL
  db:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - crm_network

  # Serviço do Backend (Laravel)
  back:
    build:
      context: ./back
    container_name: back
    ports:
      - "8000:8000"
    volumes:
      - ./back:/var/www
    depends_on:
      - db
    networks:
      - crm_network

  # Serviço do Frontend (React)
  front:
    build:
      context: ./front
    container_name: front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    depends_on:
      - back
    networks:
      - crm_network

  # Serviço para rodar comandos Artisan
  artisan:
    build:
      context: ./back
    command: >
      sh -c "php artisan migrate --force && php artisan db:seed --force"
    volumes:
      - ./back:/var/www
    depends_on:
      - back
    networks:
      - crm_network

# Volumes para persistência de dados
volumes:
  mysql_data:

# Rede comum para todos os serviços
networks:
  crm_network:
    driver: bridge
